#!/usr/bin/env bash
#
# project-constitution-stub.sh — Deterministic stand-in for
# `cap workflow run project-constitution <prompt>`.
#
# Used by tests/e2e/test-cap-project-constitution-prompt.sh via the
# CAP_PROJECT_CONSTITUTION_WORKFLOW_STUB seam in
# engine/project_constitution_runner.py:_invoke_workflow.
#
# Contract (must match what the runner expects from the real workflow):
#   - Write <idx>-draft_constitution.md under the bootstrap project's
#     run report directory:
#     ${CAP_HOME}/projects/project-constitution-bootstrap/reports/workflows/
#       project-constitution/run_<stamp>/1-draft_constitution.md
#   - Exit with the requested code so the runner can observe both
#     valid and broken workflow lifecycles.
#
# Mode is selected via CAP_STUB_MODE env (default: happy):
#   - happy           : valid fence + valid JSON → runner returns status=ok
#   - missing-fence   : draft has no canonical JSON fence → runner reports
#                       extraction_error, status=failed, repo SSOT untouched
#   - invalid-schema  : valid fence but JSON missing required fields → runner
#                       still writes the four-part snapshot but
#                       validation.json records status=failed and exit 1
#   - nonzero-exit    : valid markdown + valid JSON but stub exits 1 to
#                       simulate a workflow halt — runner coerces to failed

set -u

PROMPT="${1:-}"
MODE="${CAP_STUB_MODE:-happy}"
CAP_HOME_RESOLVED="${CAP_HOME:-${HOME}/.cap}"
RUN_PARENT="${CAP_HOME_RESOLVED}/projects/project-constitution-bootstrap/reports/workflows/project-constitution"

# Build a unique run id even when invoked rapidly within the same second:
# date stamp + PID gives us monotonically distinguishable directories per
# invocation regardless of stub mode.
STAMP="$(date -u +%Y%m%d%H%M%S)"
RUN_ID="run_${STAMP}_$(printf '%08x' "$$")"
RUN_DIR="${RUN_PARENT}/${RUN_ID}"
mkdir -p "${RUN_DIR}"

DRAFT="${RUN_DIR}/1-draft_constitution.md"

write_valid_payload() {
  cat > "${DRAFT}" <<EOF
# Project Constitution Draft (stub)

> Generated by tests/e2e/fixtures/project-constitution-stub.sh
> Prompt: ${PROMPT}

<<<CONSTITUTION_JSON_BEGIN>>>
{
  "schema_version": 1,
  "constitution_id": "stub-cap",
  "project_id": "stub-smoke",
  "name": "Stub Project Constitution",
  "summary": "Deterministic fixture used by P2 #8 e2e — never reaches real AI.",
  "source_of_truth": {
    "project_constitution": ".cap.constitution.yaml",
    "project_config": ".cap.project.yaml",
    "skill_registry": ".cap.skills.yaml"
  },
  "runtime_workspace": {
    "root": "~/.cap",
    "stores": ["projects"]
  },
  "binding_policy": {
    "defaults": {"binding_mode": "strict", "missing_policy": "halt"},
    "allowed_capabilities": ["task_constitution_planning"]
  },
  "workflow_policy": {
    "enforce_allowed_source_roots": true,
    "allowed_source_roots": ["schemas/workflows"]
  }
}
<<<CONSTITUTION_JSON_END>>>
EOF
}

case "${MODE}" in
  happy)
    write_valid_payload
    echo "stub: project-constitution happy path written to ${DRAFT}"
    exit 0
    ;;
  missing-fence)
    cat > "${DRAFT}" <<EOF
# Project Constitution Draft (stub — missing fence)

> Prompt: ${PROMPT}

The agent forgot to wrap the canonical JSON in
<<<CONSTITUTION_JSON_BEGIN/END>>> markers and also did not produce a
fenced \`\`\`json block, so extraction must fail.
EOF
    echo "stub: missing-fence draft written"
    exit 0
    ;;
  invalid-schema)
    cat > "${DRAFT}" <<EOF
# Project Constitution Draft (stub — invalid schema)

> Prompt: ${PROMPT}

<<<CONSTITUTION_JSON_BEGIN>>>
{
  "schema_version": 1,
  "constitution_id": "stub-broken",
  "project_id": "stub-smoke",
  "name": "Broken stub",
  "summary": "Missing required source_of_truth / runtime_workspace / binding_policy / workflow_policy blocks."
}
<<<CONSTITUTION_JSON_END>>>
EOF
    echo "stub: invalid-schema draft written"
    exit 0
    ;;
  nonzero-exit)
    write_valid_payload
    echo "stub: workflow halted intentionally" >&2
    exit 1
    ;;
  *)
    echo "stub: unknown CAP_STUB_MODE='${MODE}'" >&2
    exit 2
    ;;
esac
