#!/bin/bash

# ==========================================
# Agent Skills Symlink Mapper
#
# 用法：
#   bash mapper.sh              本地模式（.agents/skills/，相對路徑）
#   bash mapper.sh --global     全域模式（~/.agents/skills/，絕對路徑）
#   bash mapper.sh --uninstall  移除全域安裝
#
# SSOT 永遠是 docs/agent-skills/，此腳本只建立 symlink
# ==========================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SOURCE_DIR="${PROJECT_ROOT}/docs/agent-skills"

MODE="${1:---local}"

# ----------------------------------------------------------
# 移除全域安裝
# ----------------------------------------------------------
if [ "${MODE}" = "--uninstall" ]; then
  echo "🗑  正在移除全域安裝..."

  # --- Codex：移除 ~/.agents/skills/ 中指向本 Repo 的 symlink ---
  if [ -d "${HOME}/.agents/skills" ]; then
    find "${HOME}/.agents/skills" -type l | while read -r link; do
      target="$(readlink "${link}")"
      if [[ "${target}" == "${PROJECT_ROOT}"* ]]; then
        rm "${link}"
      fi
    done
    rmdir "${HOME}/.agents/skills" 2>/dev/null || true
    rmdir "${HOME}/.agents" 2>/dev/null || true
  fi

  # --- Codex：移除 ~/.codex/AGENTS.md ---
  if [ -f "${HOME}/.codex/AGENTS.md" ] && grep -q "charlie-ai-protocols" "${HOME}/.codex/AGENTS.md" 2>/dev/null; then
    rm "${HOME}/.codex/AGENTS.md"
    rmdir "${HOME}/.codex" 2>/dev/null || true
  fi

  # --- Claude Code：移除 ~/.claude/rules/ 中指向本 Repo 的 symlink ---
  if [ -d "${HOME}/.claude/rules" ]; then
    find "${HOME}/.claude/rules" -type l | while read -r link; do
      target="$(readlink "${link}")"
      if [[ "${target}" == "${PROJECT_ROOT}"* ]]; then
        rm "${link}"
      fi
    done
  fi

  # --- Claude Code：移除 ~/.claude/CLAUDE.md（僅當內容是本腳本產生的）---
  if [ -f "${HOME}/.claude/CLAUDE.md" ] && grep -q "charlie-ai-protocols" "${HOME}/.claude/CLAUDE.md" 2>/dev/null; then
    rm "${HOME}/.claude/CLAUDE.md"
  fi

  echo "✅ 全域安裝已移除（Codex + Claude Code）。"
  exit 0
fi

# ----------------------------------------------------------
# 決定目標路徑與 symlink 模式
# ----------------------------------------------------------
if [ "${MODE}" = "--global" ]; then
  TARGET_DIR="${HOME}/.agents/skills"
  CODEX_DIR="${HOME}/.codex"
  USE_ABSOLUTE=true
  echo "🌐 全域模式：目標 → ${TARGET_DIR}"
else
  TARGET_DIR="${PROJECT_ROOT}/.agents/skills"
  USE_ABSOLUTE=false
  echo "📁 本地模式：目標 → ${TARGET_DIR}"
fi

# 確保目標目錄存在
mkdir -p "${TARGET_DIR}"

# 清除舊的 symlink（本地模式清全部；全域模式只清指向本 Repo 的）
if [ "${USE_ABSOLUTE}" = true ]; then
  find "${TARGET_DIR}" -type l | while read -r link; do
    target="$(readlink "${link}")"
    if [[ "${target}" == "${PROJECT_ROOT}"* ]]; then
      rm "${link}"
    fi
  done
else
  find "${TARGET_DIR}" -type l -delete
fi

# ----------------------------------------------------------
# 建立 symlink
# ----------------------------------------------------------
count=0
alias_count=0

for src in "${SOURCE_DIR}"/*-agent.md; do
  [ -f "${src}" ] || continue
  filename="$(basename "${src}")"

  # 決定 symlink 來源路徑
  if [ "${USE_ABSOLUTE}" = true ]; then
    link_target="${SOURCE_DIR}/${filename}"
  else
    link_target="../../docs/agent-skills/${filename}"
  fi

  # 長名 symlink：07-qa-agent.md（供 factory.py glob *-agent.md）
  ln -sf "${link_target}" "${TARGET_DIR}/${filename}"
  count=$((count + 1))

  # 短名 symlink：qa.md（供 Codex $qa 調用）
  # 解析規則：{number}-{role_key}-agent.md → role_key.md
  short_name="$(echo "${filename}" | sed 's/^[0-9]*-//; s/-agent\.md/.md/')"
  ln -sf "${link_target}" "${TARGET_DIR}/${short_name}"
  alias_count=$((alias_count + 1))
done

echo "✅ 已建立 ${count} 個 agent symlink + ${alias_count} 個短名 alias → ${TARGET_DIR}/"

# ----------------------------------------------------------
# 全域模式：額外產生 ~/.codex/AGENTS.md
# ----------------------------------------------------------
if [ "${USE_ABSOLUTE}" = true ]; then
  # ==============================================================
  # Codex：產生全域 ~/.codex/AGENTS.md
  # ==============================================================
  mkdir -p "${CODEX_DIR}"
  cat > "${CODEX_DIR}/AGENTS.md" << AGENTS_EOF
# Charlie's AI Protocols — Global Scope

> Auto-generated by charlie-ai-protocols/scripts/mapper.sh --global
> Source: ${PROJECT_ROOT}

## Core Protocol

All agents must follow the global constitution:
${SOURCE_DIR}/00-core-protocol.md

## Git Workflow

${PROJECT_ROOT}/docs/policies/git-workflow.md

## Conventions

- All communication with the user must be in **Traditional Chinese (繁體中文)**.
- Commit messages follow Conventional Commits: \`<type>(<scope>): <subject>\`.
AGENTS_EOF

  echo "✅ 已產生 Codex 全域指令檔 → ${CODEX_DIR}/AGENTS.md"

  # ==============================================================
  # Claude Code：產生全域 ~/.claude/CLAUDE.md（使用 @ 匯入）
  # ==============================================================
  mkdir -p "${HOME}/.claude"
  cat > "${HOME}/.claude/CLAUDE.md" << CLAUDE_EOF
# Charlie's AI Protocols — Global Scope

> Auto-generated by charlie-ai-protocols/scripts/mapper.sh --global
> Source: ${PROJECT_ROOT}

## Core Protocol

@${SOURCE_DIR}/00-core-protocol.md

## Git Workflow

@${PROJECT_ROOT}/docs/policies/git-workflow.md

## Conventions

- All communication with the user must be in **Traditional Chinese (繁體中文)**.
- Commit messages follow Conventional Commits: \`<type>(<scope>): <subject>\`.
CLAUDE_EOF

  echo "✅ 已產生 Claude Code 全域指令檔 → ~/.claude/CLAUDE.md"

  # ==============================================================
  # Claude Code：symlink agents 到 ~/.claude/rules/
  # ==============================================================
  mkdir -p "${HOME}/.claude/rules"

  # 先清除舊的指向本 Repo 的 symlink
  find "${HOME}/.claude/rules" -type l | while read -r link; do
    target="$(readlink "${link}")"
    if [[ "${target}" == "${PROJECT_ROOT}"* ]]; then
      rm "${link}"
    fi
  done

  rule_count=0
  for src in "${SOURCE_DIR}"/*-agent.md; do
    [ -f "${src}" ] || continue
    filename="$(basename "${src}")"
    ln -sf "${src}" "${HOME}/.claude/rules/${filename}"
    rule_count=$((rule_count + 1))
  done

  echo "✅ 已 symlink ${rule_count} 個 agent 規則 → ~/.claude/rules/"
fi

# 詳細列表僅在 --verbose 時顯示
if [ "${VERBOSE:-}" = true ]; then
  ls -l "${TARGET_DIR}" | grep -v total
fi
