#!/usr/bin/env bash
#
# test-mapper-global-isolation.sh — P0b Provider Isolation gate.
#
# Verifies that scripts/mapper.sh --global does NOT write
# ~/.claude/CLAUDE.md or ~/.codex/AGENTS.md anymore. The previous
# behavior strapped CAP project rules onto every user's global
# claude/codex session regardless of the working directory; v0.22.x
# P0b removes those writes so project rules only load via the
# repo-local CLAUDE.md / AGENTS.md when claude/codex is invoked from
# inside the project tree.
#
# What MUST still happen (we don't break the rules sync):
#   * ~/.claude/rules/*-agent.md symlink/copy still gets refreshed
#     (passive reference, only loads via explicit @import)
#   * ~/.agents/skills/ still gets the long+short name entries
#     (Codex skill registry, opt-in $foo invocation)
#
# What MUST NOT happen anymore:
#   * ~/.claude/CLAUDE.md must not be created
#   * ~/.codex/AGENTS.md must not be created
#
# Coverage:
#   Case 1 sandbox HOME, --global mode →  ~/.claude/CLAUDE.md absent
#   Case 2 sandbox HOME, --global mode →  ~/.codex/AGENTS.md absent
#   Case 3 sandbox HOME, --global mode →  ~/.claude/rules/ populated
#   Case 4 sandbox HOME, --global mode →  ~/.agents/skills/ populated
#   Case 5 uninstall message warns about manual sections
#   Case 6 uninstall removes legacy auto-gen ~/.claude/CLAUDE.md
#                                  (only when it carries the marker)
#   Case 7 uninstall preserves user-owned ~/.claude/CLAUDE.md
#                                  (no charlie-ai-protocols marker)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
MAPPER_SH="${REPO_ROOT}/scripts/mapper.sh"

[ -f "${MAPPER_SH}" ] || { echo "FAIL: scripts/mapper.sh missing"; exit 1; }

SANDBOX_PARENT="$(mktemp -d -t cap-mapper-test.XXXXXX)"
trap 'rm -rf "${SANDBOX_PARENT}"' EXIT

pass_count=0
fail_count=0

assert_present() {
  local desc="$1" path="$2"
  if [ -e "${path}" ]; then
    echo "  PASS: ${desc}"; pass_count=$((pass_count + 1))
  else
    echo "  FAIL: ${desc}"
    echo "    expected to exist: ${path}"
    fail_count=$((fail_count + 1))
  fi
}

assert_absent() {
  local desc="$1" path="$2"
  if [ ! -e "${path}" ]; then
    echo "  PASS: ${desc}"; pass_count=$((pass_count + 1))
  else
    echo "  FAIL: ${desc}"
    echo "    must NOT exist: ${path}"
    if [ -f "${path}" ]; then
      echo "    head: $(head -3 "${path}")"
    fi
    fail_count=$((fail_count + 1))
  fi
}

assert_contains_file() {
  local desc="$1" path="$2" needle="$3"
  if [ -f "${path}" ] && grep -qF -- "${needle}" "${path}"; then
    echo "  PASS: ${desc}"; pass_count=$((pass_count + 1))
  else
    echo "  FAIL: ${desc}"
    echo "    expected file: ${path}"
    echo "    expected substring: ${needle}"
    fail_count=$((fail_count + 1))
  fi
}

assert_contains_str() {
  local desc="$1" needle="$2" haystack="$3"
  if printf '%s' "${haystack}" | grep -qF -- "${needle}"; then
    echo "  PASS: ${desc}"; pass_count=$((pass_count + 1))
  else
    echo "  FAIL: ${desc}"
    echo "    expected substring: ${needle}"
    echo "    actual head: $(printf '%s' "${haystack}" | head -3)"
    fail_count=$((fail_count + 1))
  fi
}

# ── Cases 1-4: sandbox --global run ────────────────────────────────────

echo "Case 1-4: sandbox HOME, mapper --global"
SANDBOX_HOME="${SANDBOX_PARENT}/home1"
mkdir -p "${SANDBOX_HOME}"
out_install="$(HOME="${SANDBOX_HOME}" CAP_LINK_MODE=copy bash "${MAPPER_SH}" --global 2>&1)"

assert_absent  "1. ~/.claude/CLAUDE.md NOT created"   "${SANDBOX_HOME}/.claude/CLAUDE.md"
assert_absent  "2. ~/.codex/AGENTS.md NOT created"    "${SANDBOX_HOME}/.codex/AGENTS.md"
assert_present "3. ~/.claude/rules/ populated"         "${SANDBOX_HOME}/.claude/rules"
# Spot-check at least one well-known agent file landed
assert_present "3a. ~/.claude/rules/01-supervisor-agent.md present"  "${SANDBOX_HOME}/.claude/rules/01-supervisor-agent.md"
assert_present "4. ~/.agents/skills/ populated"        "${SANDBOX_HOME}/.agents/skills"
assert_present "4a. ~/.agents/skills/01-supervisor-agent.md present" "${SANDBOX_HOME}/.agents/skills/01-supervisor-agent.md"
# Short-name alias is core mapper feature; must remain
assert_present "4b. ~/.agents/skills/supervisor.md (short name)"     "${SANDBOX_HOME}/.agents/skills/supervisor.md"

# ── Case 5: uninstall warns about manual sections ──────────────────────

echo "Case 5: uninstall message tells user about manual section risk"
SANDBOX_HOME2="${SANDBOX_PARENT}/home2"
mkdir -p "${SANDBOX_HOME2}/.claude"
# Seed a legacy auto-gen ~/.claude/CLAUDE.md so uninstall has something
# to warn about; without the seed the warning branch never fires.
cat > "${SANDBOX_HOME2}/.claude/CLAUDE.md" <<'EOF'
# Charlie's AI Protocols — Global Scope
> Auto-generated by charlie-ai-protocols/scripts/mapper.sh --global
EOF

out_uninstall="$(HOME="${SANDBOX_HOME2}" bash "${MAPPER_SH}" --uninstall 2>&1)"
assert_contains_str "5a. uninstall warns about backup"        "備份"                     "${out_uninstall}"
assert_contains_str "5b. uninstall mentions CLAUDE.md path"   "~/.claude/CLAUDE.md"      "${out_uninstall}"
assert_contains_str "5c. uninstall mentions cp backup hint"   "CLAUDE.md.backup"         "${out_uninstall}"
assert_contains_str "5d. uninstall final note v0.22.x"        "v0.22.x"                  "${out_uninstall}"

# ── Case 6: uninstall removes legacy auto-gen file ─────────────────────

echo "Case 6: uninstall removes auto-gen CLAUDE.md (carries marker)"
assert_absent "6. ~/.claude/CLAUDE.md removed by uninstall"   "${SANDBOX_HOME2}/.claude/CLAUDE.md"

# ── Case 7: uninstall preserves user-owned CLAUDE.md ───────────────────

echo "Case 7: uninstall preserves user-owned ~/.claude/CLAUDE.md (no marker)"
SANDBOX_HOME3="${SANDBOX_PARENT}/home3"
mkdir -p "${SANDBOX_HOME3}/.claude"
cat > "${SANDBOX_HOME3}/.claude/CLAUDE.md" <<'EOF'
# My personal global Claude rules
- Always answer in English.
- Cite sources for any factual claim.
EOF
HOME="${SANDBOX_HOME3}" bash "${MAPPER_SH}" --uninstall >/dev/null 2>&1
assert_present "7a. user-owned CLAUDE.md preserved"          "${SANDBOX_HOME3}/.claude/CLAUDE.md"
assert_contains_file "7b. content untouched (English line)"  "${SANDBOX_HOME3}/.claude/CLAUDE.md" "Always answer in English"

echo ""
echo "mapper-global-isolation: ${pass_count} passed, ${fail_count} failed"
[ "${fail_count}" -eq 0 ]
